// Auto-generated stub for missing module
export type SDKControlCancelRequest = any
export const SDKControlCancelRequest: any = undefined as any
export type SDKControlInitializeRequest = any
export const SDKControlInitializeRequest: any = undefined as any
export type SDKControlInitializeResponse = any
export const SDKControlInitializeResponse: any = undefined as any
export type SDKControlMcpSetServersResponse = any
export const SDKControlMcpSetServersResponse: any = undefined as any
export type SDKControlPermissionRequest = any
export const SDKControlPermissionRequest: any = undefined as any
export type SDKControlReloadPluginsResponse = any
export const SDKControlReloadPluginsResponse: any = undefined as any
export type SDKControlRequest = any
export const SDKControlRequest: any = undefined as any
export type SDKControlRequestInner = any
export const SDKControlRequestInner: any = undefined as any
export type SDKControlResponse = any
export const SDKControlResponse: any = undefined as any
export type SDKPartialAssistantMessage = any
export const SDKPartialAssistantMessage: any = undefined as any
export type StdinMessage = any
export const StdinMessage: any = undefined as any
export type StdoutMessage = any
export const StdoutMessage: any = undefined as any
