// Auto-generated stub for missing module
export type AnyZodRawShape = any
export const AnyZodRawShape: any = undefined as any
export type EffortLevel = any
export const EffortLevel: any = undefined as any
export type ForkSessionOptions = any
export const ForkSessionOptions: any = undefined as any
export type ForkSessionResult = any
export const ForkSessionResult: any = undefined as any
export type GetSessionInfoOptions = any
export const GetSessionInfoOptions: any = undefined as any
export type GetSessionMessagesOptions = any
export const GetSessionMessagesOptions: any = undefined as any
export type InferShape = any
export const InferShape: any = undefined as any
export type InternalOptions = any
export const InternalOptions: any = undefined as any
export type InternalQuery = any
export const InternalQuery: any = undefined as any
export type ListSessionsOptions = any
export const ListSessionsOptions: any = undefined as any
export type McpSdkServerConfigWithInstance = any
export const McpSdkServerConfigWithInstance: any = undefined as any
export type Options = any
export const Options: any = undefined as any
export type Query = any
export const Query: any = undefined as any
export type SDKSession = any
export const SDKSession: any = undefined as any
export type SDKSessionOptions = any
export const SDKSessionOptions: any = undefined as any
export type SdkMcpToolDefinition = any
export const SdkMcpToolDefinition: any = undefined as any
export type SessionMessage = any
export const SessionMessage: any = undefined as any
export type SessionMutationOptions = any
export const SessionMutationOptions: any = undefined as any
