import { getInitialSettings } from '../utils/settings/settings.js'

export function getSpinnerVerbs(): string[] {
  const settings = getInitialSettings()
  const config = settings.spinnerVerbs
  if (!config) {
    return SPINNER_VERBS
  }
  if (config.mode === 'replace') {
    return config.verbs.length > 0 ? config.verbs : SPINNER_VERBS
  }
  return [...SPINNER_VERBS, ...config.verbs]
}

// Void-themed spinner verbs
export const SPINNER_VERBS = [
  'Aberrating',
  'Annihilating',
  'Assembling',
  'Bending spacetime',
  'Bifurcating',
  'Black-holing',
  'Breaching',
  'Cascading',
  'Collapsing waves',
  'Compiling',
  'Computing',
  'Conjuring',
  'Converging',
  'Corrupting entropy',
  'Crystallizing',
  'Dark-mattering',
  'Decoding',
  'Decompiling',
  'Defragmenting',
  'Dematerializing',
  'Deploying',
  'Destabilizing',
  'Disassembling',
  'Dispatching',
  'Dissolving',
  'Distorting',
  'Dreaming',
  'Drifting',
  'Eclipsing',
  'Emerging',
  'Encoding',
  'Entering the void',
  'Entangling',
  'Eroding',
  'Event-horizoning',
  'Evolving',
  'Expanding',
  'Extracting',
  'Fabricating',
  'Folding dimensions',
  'Forging',
  'Fracturing',
  'Fragmenting',
  'Fusing',
  'Generating',
  'Glitching',
  'Gravitating',
  'Hacking reality',
  'Hallucinating',
  'Harmonizing',
  'Hashing',
  'Hyperjumping',
  'Hyperspacing',
  'Imploding',
  'Infiltrating',
  'Initializing',
  'Injecting',
  'Interfacing',
  'Inverting',
  'Ionizing',
  'Iterating',
  'Manifesting',
  'Materializing',
  'Merging',
  'Mutating',
  'Navigating',
  'Nebulizing',
  'Nullifying',
  'Observing',
  'Opening portals',
  'Orbiting',
  'Orchestrating',
  'Overclocking',
  'Parsing',
  'Penetrating',
  'Phasing',
  'Piercing',
  'Pipelining',
  'Propagating',
  'Pulsing',
  'Quantum-leaping',
  'Radiating',
  'Reality-bending',
  'Reassembling',
  'Recursing',
  'Refracting',
  'Rendering',
  'Resonating',
  'Reversing entropy',
  'Rift-walking',
  'Scanning',
  'Shadow-stepping',
  'Shifting',
  'Signal-boosting',
  'Singularizing',
  'Spawning',
  'Splintering',
  'Subverting',
  'Surging',
  'Synthesizing',
  'Teleporting',
  'Terraforming',
  'Threading',
  'Time-dilating',
  'Transcending',
  'Transmitting',
  'Transmuting',
  'Traversing',
  'Tunneling',
  'Unfolding',
  'Unraveling',
  'Unwinding',
  'Uploading',
  'Vectorizing',
  'Void-walking',
  'Warping',
  'Weaponizing',
  'Zeroing in',
]
