// Auto-generated stub for missing module
export type AssistantMessage = any
export const AssistantMessage: any = undefined as any
export type AttachmentMessage = any
export const AttachmentMessage: any = undefined as any
export type CollapsedReadSearchGroup = any
export const CollapsedReadSearchGroup: any = undefined as any
export type CollapsibleMessage = any
export const CollapsibleMessage: any = undefined as any
export type CompactMetadata = any
export const CompactMetadata: any = undefined as any
export type GroupedToolUseMessage = any
export const GroupedToolUseMessage: any = undefined as any
export type HookResultMessage = any
export const HookResultMessage: any = undefined as any
export type Message = any
export const Message: any = undefined as any
export type MessageOrigin = any
export const MessageOrigin: any = undefined as any
export type NormalizedAssistantMessage = any
export const NormalizedAssistantMessage: any = undefined as any
export type NormalizedMessage = any
export const NormalizedMessage: any = undefined as any
export type NormalizedUserMessage = any
export const NormalizedUserMessage: any = undefined as any
export type PartialCompactDirection = any
export const PartialCompactDirection: any = undefined as any
export type ProgressMessage = any
export const ProgressMessage: any = undefined as any
export type QueueOperationMessage = any
export const QueueOperationMessage: any = undefined as any
export type RenderableMessage = any
export const RenderableMessage: any = undefined as any
export type RequestStartEvent = any
export const RequestStartEvent: any = undefined as any
export type StopHookInfo = any
export const StopHookInfo: any = undefined as any
export type StreamEvent = any
export const StreamEvent: any = undefined as any
export type SystemAPIErrorMessage = any
export const SystemAPIErrorMessage: any = undefined as any
export type SystemAgentsKilledMessage = any
export const SystemAgentsKilledMessage: any = undefined as any
export type SystemApiMetricsMessage = any
export const SystemApiMetricsMessage: any = undefined as any
export type SystemAwaySummaryMessage = any
export const SystemAwaySummaryMessage: any = undefined as any
export type SystemBridgeStatusMessage = any
export const SystemBridgeStatusMessage: any = undefined as any
export type SystemCompactBoundaryMessage = any
export const SystemCompactBoundaryMessage: any = undefined as any
export type SystemFileSnapshotMessage = any
export const SystemFileSnapshotMessage: any = undefined as any
export type SystemInformationalMessage = any
export const SystemInformationalMessage: any = undefined as any
export type SystemLocalCommandMessage = any
export const SystemLocalCommandMessage: any = undefined as any
export type SystemMemorySavedMessage = any
export const SystemMemorySavedMessage: any = undefined as any
export type SystemMessage = any
export const SystemMessage: any = undefined as any
export type SystemMessageLevel = any
export const SystemMessageLevel: any = undefined as any
export type SystemMicrocompactBoundaryMessage = any
export const SystemMicrocompactBoundaryMessage: any = undefined as any
export type SystemPermissionRetryMessage = any
export const SystemPermissionRetryMessage: any = undefined as any
export type SystemScheduledTaskFireMessage = any
export const SystemScheduledTaskFireMessage: any = undefined as any
export type SystemStopHookSummaryMessage = any
export const SystemStopHookSummaryMessage: any = undefined as any
export type SystemThinkingMessage = any
export const SystemThinkingMessage: any = undefined as any
export type SystemTurnDurationMessage = any
export const SystemTurnDurationMessage: any = undefined as any
export type TombstoneMessage = any
export const TombstoneMessage: any = undefined as any
export type ToolUseSummaryMessage = any
export const ToolUseSummaryMessage: any = undefined as any
export type UserMessage = any
export const UserMessage: any = undefined as any
