// Auto-generated stub for missing module
export type completionHandler = any
export const completionHandler: any = undefined as any
export type errorHandler = any
export const errorHandler: any = undefined as any
export type exportHandler = any
export const exportHandler: any = undefined as any
export type logHandler = any
export const logHandler: any = undefined as any
export type taskCreateHandler = any
export const taskCreateHandler: any = undefined as any
export type taskDirHandler = any
export const taskDirHandler: any = undefined as any
export type taskGetHandler = any
export const taskGetHandler: any = undefined as any
export type taskListHandler = any
export const taskListHandler: any = undefined as any
export type taskUpdateHandler = any
export const taskUpdateHandler: any = undefined as any
