// Auto-generated stub for missing module
export type BillingType = any
export const BillingType: any = undefined as any
export type OAuthProfileResponse = any
export const OAuthProfileResponse: any = undefined as any
export type OAuthTokenExchangeResponse = any
export const OAuthTokenExchangeResponse: any = undefined as any
export type OAuthTokens = any
export const OAuthTokens: any = undefined as any
export type RateLimitTier = any
export const RateLimitTier: any = undefined as any
export type ReferralCampaign = any
export const ReferralCampaign: any = undefined as any
export type ReferralEligibilityResponse = any
export const ReferralEligibilityResponse: any = undefined as any
export type ReferralRedemptionsResponse = any
export const ReferralRedemptionsResponse: any = undefined as any
export type ReferrerRewardInfo = any
export const ReferrerRewardInfo: any = undefined as any
export type SubscriptionType = any
export const SubscriptionType: any = undefined as any
export type UserRolesResponse = any
export const UserRolesResponse: any = undefined as any
